# 错误处理
---

## 错误处理语法

JS中的错误处理使用try...catch语法。

```javascript
// 错误处理语法
try {
    command;  // 代码...
} catch(err) {  // 错误捕获, 当发生错误时调用
    console.log('err');  // 错误处理
} finally {
    console.log('over');  // 无论是否发生错误都执行
}
```

## error对象

error对象是JS的一个内建对象，发生错误时，该对象会被作为参数传递给catch。

```javascript
// 构造一个错误
let err = new Error('xx');  // 类似: SyntaxError, ReferenceError, TypeError等

// error属性
console.log(err.name);  // 错误名
console.log(err.message);  // 错误信息
console.log(err.stack);  // 当前调用栈

// 抛出错误, 语法: throw <error object>
throw err; 
```

## 自定义错误

自定义错误属于内建错误类型的扩展。

```javascript
// 自定义错误
class MyError extends Error {
    constructor(message) {
        super(message);
        this.name = "myError";
    }
}
let err = new MyError('no');  // 使用
console.log(err instanceof MyError);  // 类型推断
throw err;  // 抛出自定义错误
```

## 浏览器中错误捕获

如果在浏览器中运行脚本时发生错误，可以通过window.onerror属性捕获全局错误并发送给开放者。

```html
<script>
    window.onerror = function(message, url, line, col, error) {  // 捕获全局错误
        alert('err');  // 错误处理
    };  // message错误信息, url脚本路径, line错误行, col错误列, error为Error对象

    command;  // 错误代码
</script>
```
