# 错误处理
---

## panic/recover机制

go中的错误处理为异常抛出/捕获类似，函数panic用于抛出错误，函数recover用于捕获错误。

```go
defer func() {
    err := recover()  // 捕获错误
    if err != nil {
        fmt.Println(err.(string))
    }
}
panic("error test!")  // 抛出错误
fmt.Println("test")  // 抛出异常后, 逻辑从defer后开始
```

## error类型

error接口是另一种错误处理方式，常用于表示函数返回状态。

```go
import "errors"
func size(n int) (bool, error) {
    if n <= 2 {
        return false, errors.New("little than 2")  // 返回error类型
    }
    return true, nil
}

err := size(1)
if err != nil {
    panic(err)
}
// errors.New()和errors.Errorf()函数用于创建实现error接口的错误对象。
```

## 自定义error

通过实现errors.error接口来自定义error。

```go
type MyError struct {
    code int
    msg  string 
}

func (e *MyError) Error() string {  // 实现error接口
    return fmt.Sprintf("%s %s", e.code, e.msg)
}

func main() {
    err := func() error {
        return &MyError{code: 500, msg: "new error!"}
    }()

    if err != nil {
        fmt.Println(err)
    }
}
```
